--选人界面人物三维显示
TUNING.BLYTHE_HEALTH = 100
TUNING.BLYTHE_HUNGER = 150
TUNING.BLYTHE_SANITY = 150

TUNING.BLYTHE_BLASTER_ATTACK_RANGE = 20

TUNING.BLYTHE_BEAM_BASIC_DAMAGE = 34
TUNING.BLYTHE_BEAM_ENTER_BONUS = 5 * FRAMES
TUNING.BLYTHE_BEAM_SHOOT_TIME = 17 * FRAMES
TUNING.BLYTHE_BEAM_FREE_TIME = 26 * FRAMES
TUNING.BLYTHE_BEAM_CHAIN_BONUS = 9 * FRAMES

TUNING.BLYTHE_MISSILE_DAMAGE = 100
TUNING.BLYTHE_MISSILE_RANGE = 2
TUNING.BLYTHE_MISSILE_ENTER_BONUS = 0 * FRAMES
TUNING.BLYTHE_MISSILE_SHOOT_TIME = 17 * FRAMES
TUNING.BLYTHE_MISSILE_FREE_TIME = 26 * FRAMES
TUNING.BLYTHE_MISSILE_CHAIN_BONUS = 0 * FRAMES

--选人界面初始物品显示
TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.BLYTHE = { "blythe_blaster" }

-- 如果你的初始物品是mod物品需要定义mod物品的图片路径 比如物品是 abc
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["blythe_blaster"] = {
	atlas = "images/inventoryimages/stariliad_debug_inventoryimage.xml",
	image = "stariliad_debug_inventoryimage.tex",
}
