--选人界面人物三维显示
TUNING.BLYTHE_HEALTH = 99
TUNING.BLYTHE_HUNGER = 200
TUNING.BLYTHE_SANITY = 150

-- Blythe chop, mine and hammer actions work effectiveness
TUNING.BLYTHE_WORKEFFECTIVENESS_MODIFIER = 0.9

-- 59.5 * 0.84 = 49.98，so 2 attack with hambat can't kill a spider(100 HP)
-- Force players to use blaster instead of normal melee weapons
TUNING.BLYTHE_DAMAGE_MULT = 0.84

TUNING.BLYTHE_BLASTER_ATTACK_RANGE = 20
TUNING.BLYTHE_BLASTER_USES = 200
TUNING.BLYTHE_BLASTER_USES_UPGRADE = 200
TUNING.BLYTHE_BLASTER_USES_THRESHOLD = 1000

TUNING.BLYTHE_BEAM_BASIC_DAMAGE = 34
TUNING.BLYTHE_BEAM_SPEED = 34
TUNING.BLYTHE_BEAM_WIDE_PERCENT = 0.25
TUNING.BLYTHE_BEAM_WAVE_DAMAGE_BONUS = 17
TUNING.BLYTHE_BEAM_PLASMA_DAMAGE_BONUS = 17
-- TUNING.BLYTHE_BEAM_VS_LARGE_CREATURE_DAMAGE_MULT = 0.8
-- TUNING.BLYTHE_BEAM_VS_EPIC_DAMAGE_MULT = 0.8
-- TUNING.BLYTHE_BEAM_VS_LARGE_CREATURE_DAMAGE_DECREASE = 0
-- TUNING.BLYTHE_BEAM_VS_EPIC_DAMAGE_DECREASE = 0
-- TUNING.BLYTHE_BEAM_VS_SMALL_EPIC_DAMAGE_DECREASE = 0

TUNING.BLYTHE_PARRY_DAMAGE_MELEE = 34
TUNING.BLYTHE_BEAM_PARRY_COUNTER_DAMAGE_BONUS = 68
TUNING.BLYTHE_BEAM_PARRY_COUNTER_SPEED_BONUS = 10

TUNING.BLYTHE_BEAM_ENTER_BONUS = 5 * FRAMES
TUNING.BLYTHE_BEAM_SHOOT_TIME = 17 * FRAMES
TUNING.BLYTHE_BEAM_FREE_TIME = 26 * FRAMES
TUNING.BLYTHE_BEAM_CHAIN_BONUS = 9 * FRAMES

TUNING.BLYTHE_MISSILE_DAMAGE = 150
TUNING.BLYTHE_MISSILE_SPEED = 30
TUNING.BLYTHE_MISSILE_WORK_DAMAGE = 11
TUNING.BLYTHE_MISSILE_EXPLODE_RANGE = 1

-- Missile count upgrade
TUNING.BLYTHE_MISSILE_COUNT_INIT = 10
TUNING.BLYTHE_MISSILE_COUNT_UPGRADE = 3
TUNING.BLYTHE_MISSILE_COUNT_THRESHOLD = 99

-- Missile shoot SG
TUNING.BLYTHE_MISSILE_ENTER_BONUS = 0 * FRAMES
TUNING.BLYTHE_MISSILE_SHOOT_TIME = 17 * FRAMES
TUNING.BLYTHE_MISSILE_FREE_TIME = 26 * FRAMES
TUNING.BLYTHE_MISSILE_CHAIN_BONUS = 0 * FRAMES
-- TUNING.BLYTHE_MISSILE_ENTER_BONUS = 5 * FRAMES
-- TUNING.BLYTHE_MISSILE_SHOOT_TIME = 17 * FRAMES
-- TUNING.BLYTHE_MISSILE_FREE_TIME = 26 * FRAMES
-- TUNING.BLYTHE_MISSILE_CHAIN_BONUS = 2 * FRAMES


TUNING.BLYTHE_SUPER_MISSILE_DAMAGE = 350
TUNING.BLYTHE_SUPER_MISSILE_WORK_DAMAGE = 16
TUNING.BLYTHE_SUPER_MISSILE_EXPLODE_RANGE = 2.5

-- Super missile count upgrade
TUNING.BLYTHE_SUPER_MISSILE_COUNT_INIT = 3
TUNING.BLYTHE_SUPER_MISSILE_COUNT_UPGRADE = 1
TUNING.BLYTHE_SUPER_MISSILE_COUNT_THRESHOLD = 99

-- TUNING.BLYTHE_ICE_FOG_ENTER_BONUS = 10 * FRAMES
-- TUNING.BLYTHE_ICE_FOG_SHOOT_TIME = 17 * FRAMES
-- TUNING.BLYTHE_ICE_FOG_FREE_TIME = 26 * FRAMES
-- TUNING.BLYTHE_ICE_FOG_CHAIN_BONUS = 9 * FRAMES

TUNING.BLYTHE_ICE_FOG_SPEED = 12
TUNING.BLYTHE_ICE_FOG_LIFE_TIME = 1.75
TUNING.BLYTHE_ICE_FOG_ACCURATE = -TUNING.BLYTHE_ICE_FOG_SPEED / TUNING.BLYTHE_ICE_FOG_LIFE_TIME
TUNING.BLYTHE_ICE_FOG_SHOOT_TIME = 10 * FRAMES
TUNING.BLYTHE_ICE_FOG_FREE_TIME = 11 * FRAMES
TUNING.BLYTHE_ICE_FOG_WITHDRAW_GUN_TIME = 15 * FRAMES
TUNING.BLYTHE_ICE_FOG_CHAIN_BONUS = 10 * FRAMES

TUNING.BLYTHE_ICE_FOG_ANIM_HOLD_TIME = 10 * FRAMES
TUNING.BLYTHE_ICE_FOG_ANIM_FINISH_TIME = 27 * FRAMES

----------------------------------------------

TUNING.STARILIAD_HEXA_GHOST_MISSILE_DAMAGE = 34

--选人界面初始物品显示
TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.BLYTHE = { "blythe_blaster" }

-- 如果你的初始物品是mod物品需要定义mod物品的图片路径 比如物品是 abc
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["blythe_blaster"] = {
	atlas = "images/inventoryimages/blythe_blaster.xml",
	image = "blythe_blaster.tex",
}


----------------------------------------------

TUNING.STARILIAD_DAMAGE_NUMBER_ENABLE = GetModConfigData("damage_number")
TUNING.STARILIAD_TIP_ENABLE = GetModConfigData("tips")
TUNING.BLYTHE_TV_ENABLE = GetModConfigData("blythe_tv")
