--选人界面人物三维显示
TUNING.BLYTHE_HEALTH = 99
TUNING.BLYTHE_HUNGER = 150
TUNING.BLYTHE_SANITY = 150

TUNING.BLYTHE_BLASTER_ATTACK_RANGE = 20

TUNING.BLYTHE_BEAM_BASIC_DAMAGE = 34
TUNING.BLYTHE_BEAM_SPEED = 34
TUNING.BLYTHE_BEAM_WIDE_PERCENT = 0.25
TUNING.BLYTHE_BEAM_WAVE_DAMAGE_BONUS = 17
TUNING.BLYTHE_BEAM_PLASMA_DAMAGE_BONUS = 17

TUNING.BLYTHE_PARRY_DAMAGE_MELEE = 34
TUNING.BLYTHE_BEAM_PARRY_COUNTER_DAMAGE_BONUS = 68
TUNING.BLYTHE_BEAM_PARRY_COUNTER_SPEED_BONUS = 10

TUNING.BLYTHE_BEAM_ENTER_BONUS = 5 * FRAMES
TUNING.BLYTHE_BEAM_SHOOT_TIME = 17 * FRAMES
TUNING.BLYTHE_BEAM_FREE_TIME = 26 * FRAMES
TUNING.BLYTHE_BEAM_CHAIN_BONUS = 9 * FRAMES

TUNING.BLYTHE_MISSILE_DAMAGE = 100
TUNING.BLYTHE_MISSILE_WORK_DAMAGE = 11
TUNING.BLYTHE_MISSILE_RANGE = 1
-- TUNING.BLYTHE_MISSILE_ENTER_BONUS = 0 * FRAMES
-- TUNING.BLYTHE_MISSILE_SHOOT_TIME = 17 * FRAMES
-- TUNING.BLYTHE_MISSILE_FREE_TIME = 26 * FRAMES
-- TUNING.BLYTHE_MISSILE_CHAIN_BONUS = 0 * FRAMES
TUNING.BLYTHE_MISSILE_ENTER_BONUS = 5 * FRAMES
TUNING.BLYTHE_MISSILE_SHOOT_TIME = 17 * FRAMES
TUNING.BLYTHE_MISSILE_FREE_TIME = 26 * FRAMES
TUNING.BLYTHE_MISSILE_CHAIN_BONUS = 2 * FRAMES

TUNING.BLYTHE_SUPER_MISSILE_DAMAGE = 300
TUNING.BLYTHE_SUPER_MISSILE_WORK_DAMAGE = 16
TUNING.BLYTHE_SUPER_MISSILE_RANGE = 2.5

-- TUNING.BLYTHE_ICE_FOG_ENTER_BONUS = 10 * FRAMES
-- TUNING.BLYTHE_ICE_FOG_SHOOT_TIME = 17 * FRAMES
-- TUNING.BLYTHE_ICE_FOG_FREE_TIME = 26 * FRAMES
-- TUNING.BLYTHE_ICE_FOG_CHAIN_BONUS = 9 * FRAMES

TUNING.BLYTHE_ICE_FOG_SPEED = 12
TUNING.BLYTHE_ICE_FOG_LIFE_TIME = 1.75
TUNING.BLYTHE_ICE_FOG_ACCURATE = -TUNING.BLYTHE_ICE_FOG_SPEED / TUNING.BLYTHE_ICE_FOG_LIFE_TIME
TUNING.BLYTHE_ICE_FOG_SHOOT_TIME = 10 * FRAMES
TUNING.BLYTHE_ICE_FOG_FREE_TIME = 11 * FRAMES
TUNING.BLYTHE_ICE_FOG_WITHDRAW_GUN_TIME = 15 * FRAMES
TUNING.BLYTHE_ICE_FOG_CHAIN_BONUS = 10 * FRAMES

TUNING.BLYTHE_ICE_FOG_ANIM_HOLD_TIME = 10 * FRAMES
TUNING.BLYTHE_ICE_FOG_ANIM_FINISH_TIME = 27 * FRAMES

--选人界面初始物品显示
TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.BLYTHE = { "blythe_blaster" }

-- 如果你的初始物品是mod物品需要定义mod物品的图片路径 比如物品是 abc
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["blythe_blaster"] = {
	atlas = "images/inventoryimages/blythe_blaster.xml",
	image = "blythe_blaster.tex",
}
